### PR TITLE
Add assets

### LINKED ISSUE #1: Add assets - SVGs and images
- [x] SVG illustrations (green and purple people)
- [x] Photos (includes team photos)
- [x] SVG background accents (logo, stars, plus, zig-zags, big background blobs) - use absolute positioning

This does not include the assets for the dynamic elements and sponsor images (carousel and team modal)

### PR DESCRIPTION
**Pull request by nikhilro**
closes #1 

- [X] illustrations
- [ ] team photos
- [x]  illustrations with absolute positioning
- [x] replace all file spaces with underscore
- [x] SVG floating background accents (logo, stars, plus, zig-zags, big background blobs) - use absolute positioning

fixes needed
- [x] can't figure out a way to enlarge images to full width 
- [ ] css magic needed in places by @derrekchow 
- [x] need to debug handlebarjs
- [x] make SVG's larger (according to mocks) and use px instead of vh and vw for sizing
- [x] green blobs are in the foreground instead of behind everything (check z-index?)

### CODE REVIEW

**Comment by derrekchow** [comment]
@nikhilro Please change all file names that contain spaces with the underscore `_` (ex: `Derrek Chow.png` -> `Derrek_Chow.png`). Having spaces makes it difficult to reference files procedurally and other cases (sometime spaces get replaced by `%20`).

**Comment by derrekchow** [comment]
Still need to add SVG floating background accents

**Comment by nikhilro** [comment]
lol, why do we need to rename? it works with spaces - at least locally. have you had issues in the past?

**Comment by derrekchow** [comment]
image
Bottom footer is cut off

**Comment by nikhilro** [comment]
that's why it's in the fixes lol

**Pull request merged**
